version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant-data
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
