import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { getSession } from "~/lib/session"; // User session information
import { UserRole } from "~/lib/enums/roles";
import Link from "next/link";

import { BsBasket2 } from "react-icons/bs";
import { FaUser } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Restaurant Management",
  description: "Generated by Esma and Elif",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getSession();

  // Redirect link based on user role
  const isOwner = session?.user?.role === UserRole.OWNER;
  const accountLink = isOwner
    ? "/dashboard/profile"
    : "/dashboard/customer/account";

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="min-h-screen flex flex-col bg-gray-100">
        {/* Common Header */}
        <header className="bg-secondaryCustom text-white p-4 flex items-center justify-between shadow-lg">
          <Link href="/" className="text-2xl text-white font-bold">Byte&Bite</Link>
          <div className="flex items-center gap-4">
            {/* Account Link */}
            {session.user && session?.user?.role !== UserRole.ADMIN && (
              <div className="flex gap-6">
                <a
                  href={accountLink}
                  className="bg-white text-slate-700 px-4 py-2 rounded hover:bg-gray-200 transition flex gap-2 items-center"
                >
                  <FaUser />
                  Account
                </a>
                {session?.user?.role === UserRole.CUSTOMER && (
                  <Link
                    href="/basket"
                    className="bg-buttonColor text-white px-4 py-2 rounded hover:bg-buttonColor transition flex gap-2 items-center"
                  >
                    <BsBasket2 />
                    Basket
                  </Link>
                )}
              </div>
            )}
          </div>
        </header>

        {/* Page Content */}
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
